---
deployment:
  tasks:
    - export DEPLOYPATH="${HOME}/public_html"
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -a . "$DEPLOYPATH"
    - /usr/bin/find "$DEPLOYPATH" -type d -exec /bin/chmod 755 {} \;
    - /usr/bin/find "$DEPLOYPATH" -type f -exec /bin/chmod 644 {} \;
