---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aeessqgf/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH
    - /usr/bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /usr/bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
